CREATE TABLE t_ext_time(
	TIME_KEY			NUMBER(10),
	TIME_FULL_TIME		VARCHAR2(8 CHAR),
	TIME_PERIOD_OF_DAY	VARCHAR2(20 CHAR),
	TIME_MINUTES_AFTER_00	NUMBER(4),
	TIME_HOUR_NR		NUMBER(2),
	TIME_MINUTE_NR		NUMBER(2),
	TIME_SECOND_NR		NUMBER(2)
)
ORGANIZATION EXTERNAL
(
	TYPE oracle_loader
	DEFAULT DIRECTORY src_files
	ACCESS PARAMETERS
	(
		RECORDS DELIMITED BY newline
		CHARACTERSET AL32UTF8
		BADFILE 'time'
		DISCARDFILE 'time.dis'
		LOGFILE 'time.log'
		SKIP 1
		FIELDS TERMINATED BY ";" OPTIONALLY ENCLOSED BY '"' MISSING FIELD VALUES ARE NULL
		(
			TIME_KEY			CHAR,
			TIME_FULL_TIME		CHAR,
			TIME_HOUR_NR		CHAR,
			TIME_MINUTE_NR		CHAR,
			TIME_SECOND_NR		CHAR,
			TIME_MINUTES_AFTER_00	CHAR,
			TIME_PERIOD_OF_DAY	CHAR
		)
	)
	LOCATION ('time.csv')
)
REJECT LIMIT UNLIMITED;



CREATE TABLE t_ext_dates(
	DATE_KEY			NUMBER(10),
	DATE_FULL_DATE		VARCHAR2(10 CHAR),
	DATE_DAY_NR			NUMBER(2),
	DATE_MONTH_FULL		VARCHAR2(7 CHAR),
	DATE_MONTH_NR		NUMBER(2),
	DATE_MONTH_SHORT_NAME	VARCHAR2(3),
	DATE_MONTH_NAME		VARCHAR2(12),
	DATE_IS_HOLIDAY		VARCHAR2(3 CHAR),
	DATE_EVENT			VARCHAR2(100),
	DATE_QUARTER_FULL	VARCHAR2(7 CHAR),
	DATE_QUARTER_NR		NUMBER(1),
	DATE_SEMESTER_FULL	VARCHAR2(7 CHAR),
	DATE_SEMESTER_NR	NUMBER(1),
	DATE_YEAR			NUMBER(5)
)
ORGANIZATION EXTERNAL
(
	TYPE oracle_loader
	DEFAULT DIRECTORY src_files
	ACCESS PARAMETERS
	(
		RECORDS DELIMITED BY newline
		CHARACTERSET AL32UTF8
		BADFILE 'date.bad'
		DISCARDFILE 'date.dis'
		LOGFILE 'date.log'
		SKIP 1
		FIELDS TERMINATED BY ";" OPTIONALLY ENCLOSED BY '"' MISSING FIELD VALUES ARE NULL
		(
			DATE_KEY			CHAR,
			DATE_FULL_DATE		CHAR,
			DATE_DAY_NR			CHAR,
			DATE_MONTH_FULL		CHAR,
			DATE_MONTH_NR		CHAR,
			DATE_MONTH_SHORT_NAME	CHAR,
			DATE_MONTH_NAME		CHAR,
			DATE_IS_HOLIDAY		CHAR,
			DATE_EVENT			CHAR,
			DATE_QUARTER_FULL		CHAR,
			DATE_QUARTER_NR		CHAR(1),
			DATE_SEMESTER_FULL	CHAR,
			DATE_SEMESTER_NR		CHAR,
			DATE_YEAR			CHAR
		)
	)
	LOCATION ('dates.csv')
)
REJECT LIMIT UNLIMITED;
