/**
 * @file main.c
 * @brief Starter template with debug, memory helpers, and command-line parsing
 * @date 2025-09-26
 * @author Kauan Morinel Calheiro
 */

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>
#include <sys/types.h>
#include <sys/wait.h>

#include "debug.h"
#include "memory.h"
#include "args.h"  // generated by gengetopt

int main(int argc, char *argv[]) {
    /* Structure to store command-line arguments */
    struct gengetopt_args_info args;

    /* Parse command-line arguments */
    if (cmdline_parser(argc, argv, &args) != 0) {
        fprintf(stderr, "Error parsing arguments\n");
        return 1;
    }

    DEBUG("Arguments parsed successfully");

    /* TODO: Add main program logic here */
    printf("Program started with %d arguments\n", argc - 1);

    /* Free memory allocated by gengetopt */
    cmdline_parser_free(&args);

    DEBUG("Program finished");

    return 0;
}
